elasticsearch:
  hosts:
  - "http://user:password@elasticsearch.example.com:9200"
  index: my_index
neo4j:
  driver:
    alias: bolt
    url: "bolt://user:password@neo4j.example.com"
indexing:
  node_query: >-
    MATCH (n {uuid: $uuid})
    RETURN n {_label: labels(n), .*}
